iteam/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'product.views.handler404'
handler500 = 'product.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),

    # crud for products
    path('product/list/', views.ProductList.as_view(), name='product-list'),
    path('product/detail/<int:pk>/', views.ProductDetail.as_view(), name='product-detail'),
    path('product/list/category/<int:pk>', views.CategoryListView.as_view(), name='product-category-list'),
    path('product/list/brand/<int:pk>/', views.BrandListView.as_view(), name='product-brand-list'),
    path('product/list/super-deals/', views.SuperDealsListView.as_view(), name='product-super-deals-list'),
    path('product/list/offer/', views.OfferListView.as_view(), name='product-offer-list'),
    path('product/list/most-viewed/', views.MostViewedListView.as_view(), name='product-most-viewed-list'),
    path('search/', views.search_product, name='search-product'),    
    path('contact', views.ContactView.as_view(), name="contact"),

]

product/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime
from django.urls import reverse
from django.core.mail import send_mail


class Category(models.Model):
    name = models.CharField(max_length=100)
    category_image = models.ImageField(upload_to='category/', null=True, blank=True, help_text='Image Size: width=410px, height=281px')

    def __str__(self):
        return self.name


class Brand(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='brands')
    name = models.CharField(max_length=100)
    brand_image = models.ImageField(upload_to='brands/', null=True, blank=True, help_text="Image size: width=193px height=115px")

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.TextField()
    description = models.TextField(null=True, blank=True)
    previous_price = models.CharField(max_length=100, help_text=('e.g., Rs. 150000'), null=True, blank=True)
    new_price = models.CharField(max_length=100, help_text=('e.g., Rs. 150000'), null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name='Category', on_delete=models.CASCADE, related_name='product_category')
    brand = models.ForeignKey(Brand, verbose_name='Brand', on_delete=models.CASCADE, related_name='product_brand')
    views = models.IntegerField(default=0)
    super_deals = models.BooleanField(default=False, verbose_name='Do you want this item to display in super deals section?')
    offer = models.BooleanField(default=False, verbose_name='Does you want this item to be displayed in offer section?')
    availability = models.BooleanField(default=True, verbose_name='Is this product available in stock?')
    main_image = models.ImageField(upload_to='products/', null=True, blank=True, help_text="Image size: width=265px height=290px")
    offer_tag = models.CharField(max_length=100, null=True, blank=True, help_text="E.g. 15% off")
    visibility = models.BooleanField(default=True, verbose_name="Make this product visibile?")

    def __str__(self):
        return self.name

    def save(self):
        if self.previous_price and self.previous_price > self.new_price:
            offer = round(((int(self.previous_price) - int(self.new_price)) / int(self.previous_price)), 2) * 100
            self.offer_tag = offer
        super(Product, self).save()


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    big_image = models.ImageField(upload_to='products/big/', null=True, blank=True, help_text="Image size: width=700 px height=700px")
    thumbnail_image = models.ImageField(upload_to='products/thumbnail/', null=True, blank=True, help_text="Image size: width=100px height=100px")


class BannerImage(models.Model):
    image = models.ImageField(upload_to='banners/', help_text="Image size: width=1280px height=435px")


class Subscription(models.Model):
    email = models.EmailField(max_length=70, null=True, blank=True, unique=True)

    def __str__(self):
        return self.email


class SpecificationTitle(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class SpecificationContent(models.Model):
    title = models.ForeignKey(SpecificationTitle, on_delete=models.CASCADE, related_name="content")
    content = models.CharField(max_length=255)

    def __str__(self):
        return self.content


class ProductSpecification(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='specifications')
    title = models.ForeignKey(SpecificationTitle, on_delete=models.CASCADE, related_name="product_title")
    content = models.ForeignKey(SpecificationContent, on_delete=models.CASCADE, related_name="product_content")


class AboutITeam(models.Model):
    contact1 = models.CharField(max_length=100, default='')
    contact2 = models.CharField(max_length=100, null=True, blank=True)
    contact3 = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100)
    logo = models.ImageField(upload_to="logo/", help_text="Image size: width=192px height=31px")
    address = models.CharField(max_length=255, null=True, blank=True)
    facebook_link = models.CharField(max_length=255, null=True, blank=True)
    instagram_link = models.CharField(max_length=255, null=True, blank=True)
    youtube_link = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.email

product/forms.py
from django import forms

product/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from .models import *
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, TemplateView
from .models import Product, Category, Brand, BannerImage, ProductImage, ProductSpecification, Subscription
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.template import RequestContext


def handler404(request, *args, **argv):
    response = render_to_response('dashboard/404.html')
    response.status_code = 404
    return response

def handler500(request, *args, **argv):
    response = render_to_response('dashboard/500.html')
    response.status_code = 500
    return response


def index(request):
    super_deals = Product.objects.filter(super_deals=True, visibility=True)
    most_viewed = Product.objects.filter(views__gte=10, visibility=True)
    offer = Product.objects.filter(offer=True, visibility=True)
    brand = Brand.objects.all()
    banner = BannerImage.objects.all()
    category = Category.objects.all()
    return render(request, 'product/index.html', {'super_deals': super_deals, 'most_viewed':most_viewed, 'offer':offer, 'brand':brand, 'banner': banner, 'category': category})


class ProductList(ListView):
    template_name = 'product/product-list.html'
    model = Product
    context_object_name = 'product'
    paginate_by = 10
    queryset = Product.objects.filter(visibility=True)

    def get_queryset(self, *args, **kwargs):
        brands = self.request.GET.getlist('brands')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        brand_ids = []
        for brand_id in brands:
            brand_ids.append(int(brand_id))
        try:
            if min_price.isdigit():
                min_price = int(min_price)
            else:
                min_price = None
        except:
            min_price = None
        try:
            if max_price.isdigit():
                max_price = int(max_price)
            else:
                max_price = None
        except:
            max_price = None

        if brand_ids and min_price and max_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__range=(min_price, max_price), visibility=True)
        elif brand_ids and min_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__gte=min_price, visibility=True)
        elif brand_ids and max_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__lte=max_price, visibility=True)
        elif min_price and max_price:
            return Product.objects.filter(new_price__range=(min_price, max_price), visibility=True)
        elif brand_ids:
            return Product.objects.filter(brand_id__in=brand_ids, visibility=True)
        elif min_price:
            return Product.objects.filter(new_price__gte=min_price, visibility=True)
        elif max_price:
            return Product.objects.filter(new_price__lte=max_price, visibility=True)
        return Product.objects.filter(visibility=True)

    def get_context_data(self,**kwargs):
        context = super(ProductList,self).get_context_data(**kwargs)
        context['brands'] = Brand.objects.all()
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'product/product-detail.html'
    context_object_name = 'product'

    def get_object(self):
        id_ = self.kwargs.get("pk")
        return get_object_or_404(Product, pk=id_)

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        self.object.views += 1
        self.object.save()
        context['brands'] = Brand.objects.all()
        context['related'] = Product.objects.filter( ~Q(id=self.object.id), category=self.object.category, brand=self.object.brand, visibility=True)[:10]
        return context


class CategoryListView(ListView):
    template_name = 'product/product-list.html'
    model = Product
    context_object_name = 'product'
    paginate_by = 20

    def get_queryset(self, *args, **kwargs):
        brands = self.request.GET.getlist('brands')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        brand_ids = []
        for brand_id in brands:
            brand_ids.append(int(brand_id))
        try:
            if min_price.isdigit():
                min_price = int(min_price)
            else:
                min_price = None
        except:
            min_price = None
        try:
            if max_price.isdigit():
                max_price = int(max_price)
            else:
                max_price = None
        except:
            max_price = None

        if brand_ids and min_price and max_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__range=(min_price, max_price), category_id=self.kwargs.get("pk"), visibility=True)
        elif brand_ids and min_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__gte=min_price, category_id=self.kwargs.get("pk"), visibility=True)
        elif brand_ids and max_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__lte=max_price, category_id=self.kwargs.get("pk"), visibility=True)
        elif min_price and max_price:
            return Product.objects.filter(new_price__range=(min_price, max_price), category_id=self.kwargs.get("pk"), visibility=True)
        elif brand_ids:
            return Product.objects.filter(brand_id__in=brand_ids, category_id=self.kwargs.get("pk"), visibility=True)
        elif min_price:
            return Product.objects.filter(new_price__gte=min_price, category_id=self.kwargs.get("pk"), visibility=True)
        elif max_price:
            return Product.objects.filter(new_price__lte=max_price, category_id=self.kwargs.get("pk"), visibility=True)
        return Product.objects.filter(category_id=self.kwargs.get("pk"), visibility=True)

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['brands'] = Brand.objects.filter(category_id=self.kwargs.get('pk'))
        return context


class BrandListView(ListView):
    template_name = 'product/product-list.html'
    model = Product
    context_object_name = 'product'
    paginate_by = 20

    def get_queryset(self, *args, **kwargs):
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        try:
            if min_price.isdigit():
                min_price = int(min_price)
            else:
                min_price = None
        except:
            min_price = None
        try:
            if max_price.isdigit():
                max_price = int(max_price)
            else:
                max_price = None
        except:
            max_price = None

        if min_price and max_price:
            return Product.objects.filter(new_price__range=(min_price, max_price), brand_id=self.kwargs.get("pk"), visibility=True)
        elif min_price:
            return Product.objects.filter(new_price__gte=min_price, brand_id=self.kwargs.get("pk"), visibility=True)
        elif max_price:
            return Product.objects.filter(new_price__lte=max_price, brand_id=self.kwargs.get("pk"),  visibility=True)
        return Product.objects.filter(brand_id=self.kwargs.get("pk"), visibility=True)


class SuperDealsListView(ListView):
    template_name = 'product/product-list.html'
    model = Product
    context_object_name = 'product'
    paginate_by = 20

    def get_queryset(self, *args, **kwargs):
        brands = self.request.GET.getlist('brands')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        brand_ids = []
        for brand_id in brands:
            brand_ids.append(int(brand_id))
        try:
            if min_price.isdigit():
                min_price = int(min_price)
            else:
                min_price = None
        except:
            min_price = None
        try:
            if max_price.isdigit():
                max_price = int(max_price)
            else:
                max_price = None
        except:
            max_price = None

        if brand_ids and min_price and max_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__range=(min_price, max_price), super_deals=True, visibility=True)
        elif brand_ids and min_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__gte=min_price, super_deals=True, visibility=True)
        elif brand_ids and max_price:
            return Product.objects.filter(brand_id__in=brand_ids, new_price__lte=max_price, super_deals=True, visibility=True)
        elif min_price and max_price:
            return Product.objects.filter(new_price__range=(min_price, max_price), super_deals=True, visibility=True)
        elif brand_ids:
            return Product.objects.filter(brand_id__in=brand_ids, super_deals=True, visibility=True)
        elif min_price:
            return Product.objects.filter(new_price__gte=min_price, super_deals=True, visibility=True)
        elif max_price:
            return Product.objects.filter(new_price__lte=max_price, super_deals=True, visibility=True)
        return Product.objects.filter(super_deals=True, visibility=True)

        def get_context_data(self, *args, **kwargs):
            context = super(SuperDealsListView, self).get_context_data(**kwargs)
            context['brands'] = Brand.objects.all()
            return context

class OfferListView(ListView):

product/templates/product/add_cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
</body>
</html>

product/templates/product/index.html
{% extends 'product/base.html' %}
{% load static %}
{% load filters %}
{% block content %}
<section class="slider_and_newariv opt2_sldr">
    <div class="mainslider_holder">
        <div class="mainslider2_caro owl-carousel owl-theme">
            {% for item in banner %}
            <div class="item">
                <img src="{{ item.image.url }}" alt="">
            </div>
            {% endfor %}
            <!--item -->
        </div>
    </div>
</section>
<section class="caro_products brands">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="brdr_bx">
                    <div class="section_heading">
                        <div class="sectionheading_cont">
                            <div class="sectionttl">
                                <h2>Available Brands</h2>
                            </div>
                            <!-- <div class="vi_all_prd_caro">
                                <a href="#">View All</a>
                            </div> -->
                        </div>
                    </div>

                    <div class="brand_caro itms_caro owl-carousel owl-theme">
                            {% for item in brand %}
                        <div class="item">

                            <a href="{% url 'product:product-brand-list' item.pk %}">
                                {% if item.brand_image %}

                                <img src="{{ item.brand_image.url }}" alt="">
                                {% endif %}
                            </a>

                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<section class="caro_products">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="featured_caro_holder brdr_bx">
                    <div class="section_heading">
                        <div class="sectionheading_cont">
                            <div class="sectionttl">
                                <h2>Newly Arrived</h2>
                            </div>
                            <div class="vi_all_prd_caro">
                                <a href="{% url 'product:product-offer-list'  %}">View All</a>
                            </div>
                        </div>
                    </div>
                    <div class="thumimg_caro_itms">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="thumimg_caro itms_caro owl-carousel owl-theme">
                                    {% for item in offer %}
                                    <div class="item">
                                        <div class="list_prd_itm text-center">
                                            <div class="prd_img">
                                                <a href="{% url 'product:product-detail' item.pk %}"><img src="{{ item.main_image.url }}" alt=""></a>
                                            </div>
                                            <div class="prd_infos">
                                                <h3> <a href="{% url 'product:product-detail' item.pk %}">{{ item.name }}</a></h3>
                                                {% if item.previous_price %}<span class="price_old">Rs. {{ item.previous_price }}</span>{% endif %}
                                                <span class="price">Rs.{{ item.new_price }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- thumimg and caro -->
                </div>
            </div>
        </div>
    </div>
</section>
<section class="caro_products">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="featured_caro_holder brdr_bx">
                    <div class="section_heading">
                        <div class="sectionheading_cont">
                            <div class="sectionttl">
                                <h2>Special Offers</h2>
                            </div>
                            <div class="vi_all_prd_caro">
                                <a href="{% url 'product:product-offer-list'  %}">View All</a>
                            </div>
                        </div>
                    </div>
                    <div class="thumimg_caro_itms">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="thumimg_caro itms_caro owl-carousel owl-theme">
                                    {% for item in offer %}
                                    <div class="item">
                                        <div class="list_prd_itm text-center">
                                            <div class="prd_img">
                                                <a href="{% url 'product:product-detail' item.pk %}"><img src="{{ item.main_image.url }}" alt=""></a>
                                            </div>
                                            <div class="prd_infos">
                                                <h3> <a href="{% url 'product:product-detail' item.pk %}">{{ item.name }}</a></h3>
                                                {% if item.previous_price %}<span class="price_old">Rs. {{ item.previous_price }}</span>{% endif %}
                                                <span class="price">Rs.{{ item.new_price }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- thumimg and caro -->
                </div>
            </div>
        </div>
    </div>
</section>
{% for item in category %}
<section class="caro_products">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="featured_caro_holder brdr_bx">
                    <div class="section_heading">
                        <div class="sectionheading_cont">
                            <div class="sectionttl">
                                <h2>{{ item.name }}s</h2>
                            </div>
                            <div class="vi_all_prd_caro">
                                <a href="{% url 'product:product-category-list' item.id %}">View All</a>
                            </div>
                        </div>
                    </div>
                    <div class="featured_caro itms_caro owl-carousel owl-theme">
                        {% with item.product_category.all|separate_two as items %}
                            {% for counts in items %}
                            <div class="item">
                                {% with item|block_category:forloop.counter as category_laptops %}
                                    {% for item in category_laptops %}
                                        <div class="list_prd_itm text-center">
                                            <div class="prd_img">
                                                <a href="{% url 'product:product-detail' item.pk %}"><img src="{{ item.main_image.url }}" alt=""></a>
                                            </div>
                                            <div class="prd_infos">
                                                <h3> <a href="{% url 'product:product-detail' item.pk %}">{{ item.name }}</a></h3>
                                                {% if item.previous_price %}<span class="price_old">Rs. {{ item.previous_price }}</span>{% endif %}
                                                <span class="price">Rs.{{ item.new_price }}</span>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% endwith %}
                            </div>
                            {% endfor %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endfor %}
{% endblock %}

product/templates/product/request_product.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}
    <section class="cartpg">
        <div class="container">
            <div class="row">
                
                <div class="col-md-8">
                    <div class="crt_heading">
                    <h1>Place Order</h1>
                    </div>
                    <div class="box-checkout">
                        <form action="{% url 'product:request-product' %}" method="post" class="checkout" accept-charset="utf-8">
                            {% csrf_token %}
                            <div class="billing-fields">
                                <div class="fields-title">
                                    <h3>Order details</h3>
                                    <span></span>
                                    <div class="clearfix"></div>
                                </div>
                                <!-- /.fields-title -->
                                <div class="fields-content">
                                    <div class="field-row">
                                        <p class="field-one-half">
                                            <label for="id_product_name">Product Name *</label>
                                            {{ form.product_name }}
                                        </p>
                                        <p class="field-one-half">
                                            <label for="id_product_type">Product Type *</label>
                                            {{ form.product_type.help_text }}
                                            {{ form.product_type }}
                                        </p>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="field-row">
                                        <p class="field-one-half">
                                            <label for="id_specification">Specification *</label>
                                            {{ form.specification }}
                                        </p>
                                        <p class="field-one-half">
                                            <label for="id_contact_number">Contact Number *</label>
                                            {{ form.contact_number }}
                                        </p>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="field-row">
                                        <p class="field-one-half">
                                            <label for="id_email">Email *</label>
                                            {{ form.email }}
                                        </p>
                                        <p class="field-one-half">
                                            <label for="id_name">Full Name *</label>
                                            {{ form.name }}
                                        </p>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="field-row">
                                        <p class="field-one-half">
                                            <label for="id_amount">Quantity *</label>
                                            {{ form.amount }}
                                        </p>
                                        <div class="clearfix"></div>
                                    </div>
                                    
                                </div>
                                <!-- /.fields-content -->
                            </div>
                            <!-- /.shipping-address-fields -->
                        <!-- /.checkout -->
                        <div class="btn-order">
                            <button type="submit" class="order" id="order">Place Order</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.box-checkout -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}

product/templates/product/success_order.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}
    <section class="cartpg">
        <div class="container">
            <div class="row">
                <div class="crt_heading">
                    <h1>Your order has been placed successfully.</h1>
                </div>
                <br>
                <a href="{% url 'product:index' %}"><button class="btn btn-info">Return Home</button></a>
            </div>
        </div>
    </section>
{% endblock %}