iteam/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'product.views.handler404'
handler500 = 'product.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),

    # crud for products
    path('product/list/', views.ProductList.as_view(), name='product-list'),
    path('product/detail/<int:pk>/', views.ProductDetail.as_view(), name='product-detail'),
    path('product/list/category/<int:pk>', views.CategoryListView.as_view(), name='product-category-list'),
    path('product/list/brand/<int:pk>/', views.BrandListView.as_view(), name='product-brand-list'),
    path('product/list/super-deals/', views.SuperDealsListView.as_view(), name='product-super-deals-list'),
    path('product/list/offer/', views.OfferListView.as_view(), name='product-offer-list'),
    path('product/list/most-viewed/', views.MostViewedListView.as_view(), name='product-most-viewed-list'),
    path('search/', views.search_product, name='search-product'),    
    path('contact', views.ContactView.as_view(), name="contact"),

]

users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('profile/create/', views.ProfileCreate.as_view(), name='profile-create'),
    path('profile/update/<int:pk>/', views.ProfileUpdate.as_view(), name='profile-update'),
]

users/models.py
from django.db import models
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='profile_pics', help_text="image size: width=283px height=283px")
    address = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username + ' - ' + 'Profile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfile
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
import re
from PIL import Image

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super(UserRegisterForm, self).clean()
        password = self.cleaned_data.get('password1')
        password1 = self.cleaned_data.get('password2')
        if password != password1:
            raise ValidationError({'password1': ['The passwords did not match']})

        else:
            if password:
                if len(password) < 8:
                    raise ValidationError({'password1': ['Passwords must be of more than 8 characters']})

                pattern = re.compile(r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$")
                if not bool(pattern.search(password)):
                    raise ValidationError(
                        {'password1': ['Password must contain alphabet characters, special characters and numbers']})

    def clean_email(self):
        email = self.cleaned_data['email']
        if validate_email(email) == False:
            raise ValidationError('Enter a valid Email address')

        if User.objects.filter(email=email):
            raise ValidationError('User with this email already exists')
        else:
            return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise ValidationError('User with this username already exists')
        else:
            return username


class UserProfileForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    contact = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ['address', 'contact', 'image', 'x', 'y', 'width', 'height']

    def clean_contact(self):
        contact = self.cleaned_data.get('contact')
        pattern = re.compile(r'^\d{10}$')
        match = pattern.search(contact)
        if not pattern.search(contact):
            raise ValidationError('Enter a valid mobile number.')
        else:
            return contact

    def save(self):
        photo = super(UserProfileForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x is not None and y is not None:
            image = Image.open(photo.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((283, 283), Image.ANTIALIAS)
            resized_image.save(photo.image.path)
        return photo

users/views.py
from django.contrib.auth.decorators import login_required
from users.forms import UserRegisterForm
from django.shortcuts import render, redirect
from users.models import UserProfile
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .signup_tokens import account_activation_token
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, authenticate
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.views.generic import CreateView, DetailView, UpdateView
from .forms import UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.is_active = False
            user.save()

            mail_subject = 'Activate your account.'
            current_site = get_current_site(request)
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': settings.SITE_URL,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'users/emailnotify.html', {'email': user.email})
        else:
            username = request.POST.get('username')
            email = request.POST.get('email')
            return render(request, 'users/register.html', {
                'form': form,
                'username': username,
                'email': email,
            })
    else:
        form = UserRegisterForm()
        return render(request, 'users/register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)

        return redirect(reverse_lazy('users:profile-create'))
    else:
        return HttpResponse('Activation link is invalid!')


@login_required(login_url='/login')
def profile(request, *args, **kwargs):
    try:
        profile = UserProfile.objects.get(user_id=kwargs.get('pk'))
        return render(request, 'users/profile.html', {'profile': profile})
    except:
        return redirect(reverse_lazy('users:profile-create'))


class ProfileCreate(LoginRequiredMixin, CreateView):
    template_name = 'users/userprofile_create.html'
    form_class = UserProfileForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ProfileCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:profile', kwargs={'pk': self.request.user.pk})


class ProfileUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'users/userprofile_create.html'
    form_class = UserProfileForm

    def get_object(self):
        return UserProfile.objects.get(user_id=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('users:profile', kwargs={'pk': self.request.user.pk})

users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
https://{{domain}}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/emailnotify.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}
	<section class="pagecontent">
		<div class="container">
			<div class="row">
				<div class="entryforms login">
				    <div class="thirdprty_login">
				        <div class="formContainer p-4">
                            <h5>Activate Your Account</h5>
                            <span>An email has been sent to {{ email }}. Please activate your account by clicking the link on the email to be able to Login.</span>
                            <span>You cannot login unless project manager assigns you a role. You will receieve another email after your role assignment.
				        </div>
				        <div class="ask_users">
				            Go to home <a class="float-right" href="{% url 'product:index' %}">Home</a>
				        </div>
				    </div>
				</div>
			</div>
		</div>
    </section>
{% endblock %}

users/templates/users/login.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}
	<section class="pagecontent">
		<div class="container">
			<div class="row">
				<div class="entryforms login">
				    <div class="thirdprty_login">
				        <div class="formContainer p-4">
				            <form method='post' action=".">
								{% csrf_token %}
								{% if form.errors %}
									<div class="error-top">
										<p>Login Failed</p>
									</div>
								{% endif %}
				                <div class="form-group">
				                    <label>Username</label>
									<input type="text" class="form-control" name="username">
				                </div>
				                <div class="form-group">
				                    <label>Password</label>
				                    <a class="float-right" href="{% url 'password_reset' %}">Forgot Password?</a>
									<input type="password" class="form-control" name="password">
										
								</div>
								<input type="hidden" name="next" value="{{ next }}">
								{% if form.errors %}
								<div class="error-bottom">
									<p>Check If:</p>
									<p>1. Username and password matches.</p>
									<p>2. You have activated your account.</p>
								</div>
								{% endif %}
				                <button type="submit" class="sbt_btn">Login</button>
				            </form>
				        </div>
				        <div class="ask_users">
				            Don't have an account? <a class="float-right" href="{% url 'users:register' %}">Sign up</a>
				        </div>
				    </div>
				</div>
			</div>
		</div>
    </section>
{% endblock %}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Logout</title>
</head>
<body>
    <h2>You have Been Logged Out</h2>
    <div class="content-section">

        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login'  %}" class="font-inc underline">Log In Again</a>
            </small>

        </div>

    </div> 
</body>
</html>

users/templates/users/password_reset.html
{% extends 'product/base.html' %}
{% load static %}
{% block content %}
    <section class="cartpg">
        <div class="container">
            <div class="row">
                
                <div class="col-md-8 mx-auto">
                    <div class="crt_heading">
                    <h1>Forgot Password?</h1>
                    </div>
                    <div class="box-checkout">
                        <div class="checkout-login">
                            Please enter your email to get reset link...
                        </div>
                        <form action="." method="post" class="checkout" accept-charset="utf-8">
                            {% csrf_token %}
                            <div class="billing-fields">
                                <!-- /.fields-title -->
                                <div class="fields-content">
                                    <div class="row">
                                    <div class="col-md-6">
                                        <p class="field-one-half">
                                            <input type="text" id="first-name" name="email" placeholder="Your email address here...">
                                        </p>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="sendlnk_bx">
                                                <button type="submit" class="sbt_btn">Reset</button>
                                        </p>
                                    </div> 
                                    </div>
                                </div>
                                <!-- /.fields-content -->
                            </div>
                            <!-- /.shipping-address-fields -->
                        </form>
                        <!-- /.checkout -->
                    </div>
                    <!-- /.box-checkout -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="content-section">
        <p>
            Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login</a> now.
        </p>

    </div> 
</body>
</html>

users/templates/users/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reset Confirm</title>
</head>
<body>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>

    </div> 
</body>
</html>

users/templates/users/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Reset Done</title>
</head>
<body>
    <div class="alret alert-info">
        An email has been sent with instructions to reset your password 

    </div>
</body>
</html>

users/templates/users/profile.html
{% extends 'product/base.html' %}
{% block content %}
    <section class="cartpg">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <div class="box-checkout profile__edit__head">
                        <div class="checkout-login adprd_heading">
                            <div class="crt_heading">
                                <h1>My Account</h1>
                            </div>
                            <a class="prof__edit" href="{% url 'users:profile-update' request.user.pk %}">Edit</a>
                        </div>
                    </div>
                    <div class="user__infos__profile">
                        <h2>General Information</h2>
                        <div class="prof__infos__list">
                            <label>User Name</label>
                            <span class="info__text">{{ profile.user.username }}</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>User Profile Image</label>
                            <span class="info__text">
                                <img src="{{ profile.image.url }}" alt="">
                            </span>                            
                        </div>
                        <div class="prof__infos__list">
                            <label>Address</label>
                            <span class="info__text">{{ profile.address }}</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>Email</label>
                            <span class="info__text">{{ profile.user.email }}</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>Phone Number</label>
                            <span class="info__text">{{ profile.contact }}</span>
                        </div>
                    </div>
                    <!-- <div class="user__infos__profile">
                        <h2>Shipping Information</h2>
                        <div class="prof__infos__list">
                            <label>Address Two</label>
                            <span class="info__text">Kathmandu Nepal</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>Address</label>
                            <span class="info__text">Kathmandu</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>Email</label>
                            <span class="info__text">bimalpariyar1@gmail.com</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>Phone Number</label>
                            <span class="info__text">9864595211</span>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}

users/templates/users/register.html
{% extends 'product/base.html' %}	
{% load static %}
{% block content %}
	<section class="pagecontent">
		<div class="container">
			<div class="row">
				<div class="entryforms signup">
				    <h1>Create your account. It’s free and only takes a minute.</h1>

				    <div class="formContainer p-4">
				        <form method="post" action=".">
                            {% csrf_token %}
				            <div class="form-group">
				                <label>Username</label>
								<input type="text" name="username" class="form-control">
								{% if form.username.errors %}
									{{ form.username.errors }}
								{% endif %}
				            </div>
				            <div class="form-group">
				                <label>Email address</label>
								<input type="email" name="email" class="form-control">
								{% if form.email.errors %}
									{{ form.email.errors }}
								{% endif %}
				            </div>
				            <div class="form-group">
				                <label>Password</label>
								<input type="password" name="password1" class="form-control">
								{% if form.password1.errors %}
									{{ form.password2.errors }}
								{% endif %}
				                <div class="form_instructions">
				                    <p>Passwords must contain at least eight characters, including at least one letter and one number.</p>
				                </div>
                            </div>
                            <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" name="password2" class="form-control">
                                    <div class="form_instructions">
                                        <p>Both Passwords must match.</p>
                                    </div>
                                </div>
				            <button type="submit" class="sbt_btn">Signup</button>
				        </form>
				        <div class="sigup_agree">
				            By clicking “Sign up”, you agree to our <a href="#">terms of service</a>, <a href="#">privacy policy</a>.
				        </div>
				    </div>
				    <div class="ask_users">
				        Already have an account? <a class="float-right" href="{% url 'login' %}">Login Now</a>
				    </div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

users/templates/users/userprofile_create.html
{% extends 'product/base.html' %}
{% block content %}
    <section class="cartpg">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <div class="box-checkout profile__edit__head">
                        <div class="checkout-login adprd_heading">
                            <div class="crt_heading">
                                <h1>Edit Account</h1>
                            </div>
                        </div>
                    </div>
                    <div class="user__infos__profile">
                        <h2>General Information</h2>
                        <div class="prof__infos__list">
                            <label>User Name</label>
                            <span class="info__text">{{ request.user.username }}</span>
                        </div>
                        <div class="prof__infos__list">
                            <label>Email</label>
                            <span class="info__text">{{ request.user.email }}</span>
                        </div>
                        <form method="post" action="." enctype="multipart/form-data" id="formUpload">
                            {% csrf_token %}
                            <div class="prof__infos__list">
                                <label>User Profile Image</label>
                                <span class="info__text">
                                    {{ form.image }}
                                </span>                            
                            </div>
                            {{ form.x }}
                            {{ form.y }}
                            {{ form.width }}
                            {{ form.height }}
                            <div class="prof__infos__list">
                                <label>Address</label>
                                {{ form.address }}
                            </div>
                            <div class="prof__infos__list">
                                <label>Phone Number</label>
                                {{ form.contact }}
                            </div>
                            <div class="btn-order">
                                <button type="submit" class="">Submit</button>
                            </div>
                        </form>
                        <div class="modal fade" id="modalCrop">
                            <div class="modal-dialog">
                              <div class="modal-content">
                                <div class="modal-header">
                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                  <h4 class="modal-title">Crop the photo</h4>
                                </div>
                                <div class="modal-body">
                                  <img src="" id="image" style="max-width: 100%;">
                                </div>
                                <div class="modal-footer">
                                  <div class="btn-group pull-left" role="group">
                                    <button type="button" class="btn btn-default js-zoom-in">
                                      <span class="glyphicon glyphicon-zoom-in"></span>
                                    </button>
                                    <button type="button" class="btn btn-default js-zoom-out">
                                      <span class="glyphicon glyphicon-zoom-out"></span>
                                    </button>
                                  </div>
                                  <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                                  <button type="button" class="btn btn-primary js-crop-and-upload">Crop</button>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
  <script>
    $(function () {
      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_image").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });
      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 283/283,
          minCropBoxWidth: 283,
          minCropBoxHeight: 283,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });
      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });
      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });
      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#modalCrop").modal("hide");
      });
    });
  </script>
{% endblock %}