dashboard/urls.py
from django.urls import path, re_path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),

    # crud for categories
    path('category/list/', views.CategoryList.as_view(), name='category-list'),
    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category/<int:pk>/delete/', views.CategoryDelete.as_view(), name='category-delete'),
    path('category/<int:pk>/update/', views.CategoryUpdate.as_view(), name='category-update'),
    re_path(r'^add/specform-(?P<id>\d+)-title/$', views.newSpecificationTitle, name="title"),
    path('add/title/', views.newSpecificationTitle, name="title"),
    re_path(r'^add/specform-(?P<id>\d+)-content/$', views.newSpecificationContent, name="title"),
    path('add/content/', views.newSpecificationContent, name="content"),


    # crud for brands
    path('add/brand/', views.newBrand, name="brand"),
    path('brand/list/', views.BrandList.as_view(), name='brand-list'),
    path('brand/create/', views.BrandCreate.as_view(), name='brand-create'),
    path('brand/<int:pk>/delete/', views.BrandDelete.as_view(), name='brand-delete'),
    path('brand/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand-update'),

    # crud for banner images
    path('banner/list/', views.BannerList.as_view(), name='banner-list'),
    path('banner/create/', views.BannerCreate.as_view(), name='banner-create'),
    path('banner/<int:pk>/delete/', views.BannerDelete.as_view(), name='banner-delete'),
    path('banner/<int:pk>/update/', views.BannerUpdate.as_view(), name='banner-update'),

    path('product/list/', views.ProductList.as_view(), name="product-list"),
    path('product/create/', views.ProductCreate.as_view(), name='product-create'),
    path('product/<int:pk>/delete/', views.ProductDelete.as_view(), name='product-delete'),
    path('product/<int:pk>/update/', views.ProductUpdate.as_view(), name='product-update'),

    path('specification/list', views.SpecificationList.as_view(), name='specification-list'),
    path('specification/add', views.SpecificationCreate.as_view(), name='specification-create'),
    path('specification/<int:pk>/update', views.SpecificationUpdate.as_view(), name="specification-update"),
    path('specification/<int:pk>/delete', views.SpecificationDelete.as_view(), name="specification-delete"),

    path('specification/<int:pk>/content/list', views.SpecificationContentList.as_view(), name="specification-content-list"),
    path('specification/<int:spec_id>/content/<int:pk>/delete', views.SpecificationContentDelete.as_view(), name="specification-content-delete"),

    path('about/create/', views.AboutCreate.as_view(), name='about-create'),
    path('about/<int:pk>/update/', views.AboutUpdate.as_view(), name='about-update'),

    path('product/<int:pk>/image/list/', views.ProductImageList.as_view(), name="product-images-list"),
    path('product/<int:product_id>/image/<int:pk>/delete/', views.ProductImageDelete.as_view(), name="product-image-delete"),
    path('product/<int:pk>/specification/list/', views.ProductSpecificationList.as_view(), name="product-specification-list"),
    path('product/<int:product_id>/specification/<int:pk>/delete/', views.ProductSpecificationDelete.as_view(), name="product-specification-delete"),
    # path('product/<int:product_id>/specification/<int:pk>/edit', views.ProductSpecificationEdit.as_view(), name="product-specification-edit"),

]

iteam/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'product.views.handler404'
handler500 = 'product.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('user/', include('users.urls', namespace='users')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/login.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='profile_pics', help_text="image size: width=283px height=283px")
    address = models.CharField(max_length=255)
    contact = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username + ' - ' + 'Profile'

dashboard/forms.py
from django import forms
from product.models import Product, Category, Brand, BannerImage, ProductSpecification, \
    ProductImage, SpecificationTitle, SpecificationContent, AboutITeam
from django.forms.models import inlineformset_factory
from PIL import Image
from .widgets import *


class ProductForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    brand = forms.ModelChoiceField(Brand.objects, widget=SelectWithPop)

    class Meta:
        model = Product
        fields = ['name', 'description', 'previous_price', 'new_price', 'category', 'brand', 'super_deals', 'offer', 'availability', 'main_image', 'visibility', 'x', 'y', 'width', 'height']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(**kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['previous_price'].widget.attrs['class'] = 'form-control'
        self.fields['new_price'].widget.attrs['class'] = 'form-control'
        self.fields['category'].widget.attrs['class'] = 'form-control'
        self.fields['brand'].widget.attrs['class'] = 'form-control'
        self.fields['super_deals'].widget.attrs['class'] = 'form-control'
        self.fields['offer'].widget.attrs['class'] = 'form-control'
        self.fields['availability'].widget.attrs['class'] = 'form-control'
        self.fields['main_image'].widget.attrs['class'] = 'form-control'
        self.fields['visibility'].widget.attrs['class'] = 'form-control'

    def save(self):
        photo = super(ProductForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x is not None and y is not None:
            image = Image.open(photo.main_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((265, 290), Image.ANTIALIAS)
            resized_image.save(photo.main_image.path)
        return photo


class CategoryForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ['name', 'category_image', 'x', 'y', 'width', 'height']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['category_image'].widget.attrs['class'] = 'form-control'

    def save(self):
        photo = super(CategoryForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x is not None and y is not None:
            image = Image.open(photo.category_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((410, 281), Image.ANTIALIAS)
            resized_image.save(photo.category_image.path)
        return photo


class BrandForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Brand
        fields = ['category', 'name', 'brand_image', 'x', 'y', 'width', 'height']

    # def __init__(self, *args, **kwargs):
    #     super(BrandForm, self).__init__(**kwargs)
    #     self.fields['name'].widget.attrs.update({'class': 'form-control'})
    #     self.fields['category'].widget.attrs.update({'class': 'form-control'})
    #     self.fields['brand_image'].widget.attrs.update({'class': 'form-control'})

    def save(self):
        photo = super(BrandForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x is not None and y is not None:
            image = Image.open(photo.brand_image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((193, 115), Image.ANTIALIAS)
            resized_image.save(photo.brand_image.path)
        return photo


class BannerImageForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = BannerImage
        fields = ['image', 'x', 'y', 'width', 'height']

    def __init__(self, *args, **kwargs):
        super(BannerImageForm, self).__init__(**kwargs)
        self.fields['image'].widget.attrs.update({'class': 'form-control'})

    def save(self, *args, **kwargs):
        photo = super(BannerImageForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        if x is not None and y is not None:
            image = Image.open(photo.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((1280, 435), Image.ANTIALIAS)
            resized_image.save(photo.image.path)
        return photo


class ProductSpecificationForm(forms.ModelForm):
    title = forms.ModelChoiceField(SpecificationTitle.objects, widget=SelectWithPop)
    content = forms.ModelChoiceField(SpecificationContent.objects, widget=SelectWithPop)

    class Meta:
        model = ProductSpecification
        fields = ['title', 'content']


class ProductImageForm(forms.ModelForm):
    x_main = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y_main = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width_main = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height_main = forms.FloatField(widget=forms.HiddenInput(), required=False)

    x_thumb = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y_thumb = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width_thumb = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height_thumb = forms.FloatField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(ProductImageForm, self).__init__(*args, **kwargs)
        self.fields['big_image'].widget.attrs.update({'class': 'big_image_class'})
        self.fields['thumbnail_image'].widget.attrs.update({'class': 'thumb_image_class'})

    class Meta:
        model = ProductImage
        fields = ['big_image', 'thumbnail_image', 'x_main', 'y_main', 'width_main', 'height_main', 'x_thumb', 'y_thumb', 'width_thumb', 'height_thumb']

    def save(self, commit=True):
        photo = super(ProductImageForm, self).save(commit=False)

        x_main = self.cleaned_data.get('x_main')
        y_main = self.cleaned_data.get('y_main')
        w_main = self.cleaned_data.get('width_main')
        h_main = self.cleaned_data.get('height_main')

        x_thumb = self.cleaned_data.get('x_thumb')
        y_thumb = self.cleaned_data.get('y_thumb')
        w_thumb = self.cleaned_data.get('width_thumb')
        h_thumb = self.cleaned_data.get('height_thumb')

        if x_main is not None and y_main is not None:
            image = Image.open(photo.big_image)
            cropped_image = image.crop((x_main, y_main, w_main+x_main, h_main+y_main))
            resized_image = cropped_image.resize((700, 700), Image.ANTIALIAS)
            resized_image.save(photo.big_image.path)

        if x_thumb is not None and y_thumb is not None:
            image = Image.open(photo.thumbnail_image)
            cropped_image = image.crop((x_thumb, y_thumb, w_thumb + x_thumb, h_thumb + y_thumb))
            resized_image = cropped_image.resize((100, 100), Image.ANTIALIAS)
            resized_image.save(photo.thumbnail_image.path)
        if commit:
            photo.save()
        else:
            return photo


ProductImageFormset = inlineformset_factory(Product, ProductImage, form=ProductImageForm, fields=['big_image', 'thumbnail_image', 'x_main', 'y_main', 'width_main', 'height_main', 'x_thumb', 'y_thumb', 'width_thumb', 'height_thumb'], extra=1, max_num=10)
ProductSpecificationFormset = inlineformset_factory(Product, ProductSpecification, form=ProductSpecificationForm, fields=['title', 'content'], extra=1, max_num=20)


class SpecificationTitleForm(forms.ModelForm):
    class Meta:
        model = SpecificationTitle
        fields = ('title',)


class SpecificationContentForm(forms.ModelForm):
    class Meta:
        model = SpecificationContent
        fields = ('title', 'content')


SpecificationContentFormset = inlineformset_factory(SpecificationTitle, SpecificationContent, form=SpecificationContentForm, fields=['title', 'content'], extra=1, max_num=20)


class AboutForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = AboutITeam

dashboard/templates/dashboard/add-banner.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
        <div class="single-pro-review-area mt-t-30 mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-payment-inner-st">
                            <div id="myTabContent" class="tab-content custom-product-edit">
                                <div class="product-tab-list tab-pane fade active in" id="description">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                            <div class="review-content-section">
                                                <div id="dropzone1" class="pro-ad">
                                                    <form action='.' method="POST" enctype="multipart/form-data" class="dropzone dropzone-custom needsclick add-professors" id="demo1-upload">
                                                        {% csrf_token %}
                                                        <div class="row">
                                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                                <div class="form-group">
                                                                    {{ form.image.label }}
                                                                    {{ form.image }}
                                                                    {{ form.image.help_text }}
                                                                </div>
                                                                {{ form.x }}
                                                                {{ form.y }}
                                                                {{ form.width }}
                                                                {{ form.height }}
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-lg-12">
                                                                <div class="payment-adress">
                                                                    <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="modalCrop">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
              </div>
              <div class="modal-body">
                <img src="" id="image" style="max-width: 100%;">
              </div>
              <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                  <button type="button" class="btn btn-default js-zoom-in">
                    <span class="glyphicon glyphicon-zoom-in"></span>
                  </button>
                  <button type="button" class="btn btn-default js-zoom-out">
                    <span class="glyphicon glyphicon-zoom-out"></span>
                  </button>
                </div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                <button type="button" class="btn btn-primary js-crop-and-upload">Crop</button>
              </div>
            </div>
          </div>
        </div>
        {% endblock %}
        {% block scripts %}
        <script>
          $("#banner-nav").addClass('active');
          $("#banner-nav ul").addClass('show');
        </script>
        <script src="{% static 'dashboard/js/cropper/cropper.min.js' %}"></script>
        <script>
          $(function () {
            /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
            $("#id_image").change(function () {
              if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                  $("#image").attr("src", e.target.result);
                  $("#modalCrop").modal("show");
                }
                reader.readAsDataURL(this.files[0]);
              }
            });
            /* SCRIPTS TO HANDLE THE CROPPER BOX */
            var $image = $("#image");
            var cropBoxData;
            var canvasData;
            $("#modalCrop").on("shown.bs.modal", function () {
              $image.cropper({
                viewMode: 1,
                aspectRatio: 3/1,
                ready: function () {
                  $image.cropper("setCanvasData", canvasData);
                  $image.cropper("setCropBoxData", cropBoxData);
                }
              });
            }).on("hidden.bs.modal", function () {
              cropBoxData = $image.cropper("getCropBoxData");
              canvasData = $image.cropper("getCanvasData");
              $image.cropper("destroy");
            });
            $(".js-zoom-in").click(function () {
              $image.cropper("zoom", 0.1);
            });
            $(".js-zoom-out").click(function () {
              $image.cropper("zoom", -0.1);
            });
            /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
            $(".js-crop-and-upload").click(function () {
              var cropData = $image.cropper("getData");
              $("#id_x").val(cropData["x"]);
              $("#id_y").val(cropData["y"]);
              $("#id_height").val(cropData["height"]);
              $("#id_width").val(cropData["width"]);
              $("#modalCrop").modal("hide");
            });
          });
        </script>
        {% endblock %}

dashboard/templates/dashboard/banner-list.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>Banner Images List</h4>
                            <div class="add-product">
                                <a href="{% url 'dashboard:banner-create' %}">Add Banner Image</a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>No</th>
                                        <th>Banner Image</th>
                                        <th>Setting</th>
                                    </tr>
                                    {% for item in banner %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        {% if item.image %}
                                        <td><img src="{{ item.image.url }}" alt="" /></td>
                                        {% else %}
                                        <td><img src="" alt="image"></td>
                                        {% endif %}
                                        <td>
                                            <a href="{% url 'dashboard:banner-update' item.pk %}" data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                            <form method="get" action="{% url 'dashboard:banner-delete' item.pk %}">
                                              <button type="submit" data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                            {% if is_paginated %}
                            <div class="custom-pagination">
              								<ul class="pagination">
                                {% if page_obj.has_previous %}
              									<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                {% endif %}
                                {% for i in paginator.page_range %}
              									    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
              									    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                {% endif %}
              								</ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
        {% block scripts %}
        <script>
          $("#banner-nav").addClass('active');
          $("#banner-nav ul").addClass('show');
        </script>
        {% endblock %}

dashboard/templates/dashboard/product-list.html
{% extends 'dashboard/base.html' %}
{% block content %}
{% load static %}
        <div class="product-status mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>Product List</h4>
                            <div class="add-product">
                                <a href="{% url 'dashboard:product-create' %}">Add Product</a>
                            </div>
                            <div class="asset-inner">
                                <table>
                                    <tr>
                                        <th>No</th>
                                        <th>Image</th>
                                        <th>Name of Product</th>
                                        <th>Category</th>
                                        <th>Brand</th>
                                        <th>Type</th>
                                        <th>Current Price</th>
                                        <th>Images</th>
                                        <th>Specifications</th>
                                        <th>Setting</th>
                                    </tr>
                                    {% for item in product %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        {% if item.main_image %}
                                        <td><img src="{{ item.main_image.url }}" alt="" /></td>
                                        {% else %}
                                        <td><img src="" alt="image"></td>
                                        {% endif %}
                                        <td>{{ item.name }}</td>
                                        <!-- <td>
                                            <button class="pd-setting">Active</button>
                                        </td> -->
                                        <td>{{ item.category.name }}</td>
                                        <td>{{ item.brand.name }}</td>
                                        <td>{{ item.product_type.name }}</td>
                                        <td>{{ item.new_price }}</td>
                                        <td>
                                          <a href="{% url 'dashboard:product-images-list' item.pk %}"><button class="btn btn-primary">View Images</button></a>
                                        </td>
                                        <td>
                                          <a href="{% url 'dashboard:product-specification-list' item.pk %}"><button class="btn btn-primary">View Specifications</button></a>
                                        </td>
                                        <td>
                                            <a href="{% url 'dashboard:product-update' item.pk %}" data-toggle="tooltip" title="Edit" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                            <form method="get" action="{% url 'dashboard:product-delete' item.pk %}">
                                              <button type="submit" data-toggle="tooltip" title="Trash" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </table>
                            </div>
                            {% if is_paginated %}
                            <div class="custom-pagination">
              								<ul class="pagination">
                                {% if page_obj.has_previous %}
              									<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                {% endif %}
                                {% for i in paginator.page_range %}
              									    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endfor %}
                                {% if page_obj.has_next %}
              									    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                {% endif %}
              								</ul>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
        {% block scripts %}
        <script>
          $("#product-nav").addClass('active');
          $("#product-nav ul").addClass('show');
        </script>
        {% endblock %}